### ISSUE TITLE
[V2] Docker requirement appears to be a show stopper in VMWare environments.

### ISSUE THREAD

**Issue by PtwHub** [Azure/iot-edge-v1#477]
Hi. In version 1 of Edge, we could install an executable and configure it. There were few(er) dependencies. The irony/paradox of the V2 Docker requirement is that it increases the dependencies: docker is apparently now required in the installation and runtime environment? Please confirm. 

Many corporate IT departments have central NetApp+VMware infrastructures. This is fine for running windows UNTIL you have a Docker dependency, then (currently) nothing works. The constellation Docker on Windows does not work on VMWare. So, what is a designer to do when targeting corporate IT-departments worldwide?

Thanks for a clear strategy here so we can decide whether IoT-Edge is an option for us.

**Comment by aribeironovaes** [comment]
Thanks for your input @PtwHub , 

I will bring your concerns and very good point to our team for consideration. 

I can say though that although we are using docker now, our design if very open for other type of images/container. 

It is definitely on our radar to consider other environment, but docker right now is the one we chose as a short term goals. 

We will let you know once we know more about it. 
Thanks, 

Angelo Ribeiro.

**Comment by PtwHub** [comment]
Thanks Angelo. OK, we have confidence that these issues will be addressed. Please keep the "special but common" Use-Case of a single-source Edge solution with a pure OnPrem Option (Install and use without internet connection) in the design/docs. Looking forward.

**Comment by Zuendelmeister** [comment]
Hi all,

it is important to know that docker is problematic  in windows environments (virtualization and overhead). I suggest to try the Edge_V2 on a linux based environment (if possible), which works way easier much more stable.

Best regards,
Zuendelmeister

**Comment by PtwHub** [comment]
Hi Z, yes this is our fallback but we expect Microsoft to have a viable solution on their own servers -- as we also have MSSQL dependencies OnPrem. There are also IT-centers that prefer the NetApp/VMWare infrastructures which appears to be the worst case with windows. OK, all this could potentially run on Linux boxes but currently not the preferred deployment scenario/requirement for customer sites.

Thanks!

**Comment by damonbarry** [comment]
Hey @PtwHub would you mind adding this to the [Azure feedback portal](https://feedback.azure.com/forums/907045-azure-iot-edge)? I believe that will be a better place to track this feature request.

**Comment by aribeironovaes** [comment]
Closing so a new issue can be added on v2 github or at the Azure feedback portal (which is the right place for this request. )
