### ISSUE TITLE
[V2] std::bad_alloc error

### ISSUE THREAD

**Issue by dariuszparys** [Azure/iot-edge-v1#484]
This error just happens on ARM (Raspberry Pi).

If I use `SetDesiredPropertyUpdateCallbackAsync` in a custom module which is just pumping data into the EdgeHub and I call once a module twin update through the Azure CLI like in the sample below

```
az iot hub module-twin replace -n codin -d rpi-temp-demo -m tempSensor -j module-twin.json
``` 

the custom module is stopping sending data after several calls to `SendEventAsync`. When looking in the logs of the EdgeHub I see then the following line

```
2018-01-22 11:48:33.461 +00:00 [INF] - Binding message channel for device Id rpi-temp-demo/tempSensor
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

The same code is running fine in Linux-x64.

**Comment by damonbarry** [comment]
This is the 2nd report I've seen of `std::bad_alloc` exceptions on RPi. @dariuszparys can you attach the code for the custom module (inline or gist)? Also, are there any other modules running or devices connected? What do the routes look like on Edge Hub? If we can repro locally we should be able to figure out what's going on...

**Comment by dariuszparys** [comment]
This is currently a work in progress module, so here is the link to the code I used here https://github.com/Azure/azureiotedge-simulated-temperature-sensor/pull/2. The image itself can be pulled from `dariuszparys/azureiotedge-simulated-temperature-sensor:twin-linux-arm`. No other modules involved and the route is just the default one created by the portal, so no changes there. I'm just pushing into `temperatureOutput` @damonbarry I added you to the repo as it is currently private

**Comment by damonbarry** [comment]
It looks like the Edge Hub is dying in this particular scenario. `std::bad_alloc` is an exception thrown by the C++ standard library, and the only native component I can think of in Edge Hub is RocksDb (used as a durable queue for messages, twin updates, etc.). So I suspect RocksDb is involved by I'm not sure how.

I'm marking this as a bug, and we'll do more investigation.

**Comment by aribeironovaes** [comment]
Closing this issue since we have a set of fixes on this area. If you see that again, please open a new github issue here: https://github.com/Azure/iotedge
