### ISSUE TITLE
[v2] Transparent deep packet inspection proxy for IOT Edge Modules / Container

### ISSUE THREAD

**Issue by SergeiIkkert** [Azure/iot-edge-v1#496]
We ran into nearly the same problems as [#465](https://github.com/Azure/iot-edge/issues/465) when using Azure IOT EDGE with a transparent deep packet inspection proxy. Due to security reasons, many of our customers use transparent proxies that decrypt the traffic for deep packet inspection and re-encrypt it afterwards. With this solution, the proxy for a device looks almost transparent and no login data is required. Authentication takes place exclusively via the network infrastructure (e. g. IP address). Due to the local re-encryption, TLS connections can only be established by installing the CA certificate of the proxy on a device. Otherwise connections fail due to certificate errors. On Linux and Windows hosts, this approach is usually not a problem, since you can simply install a new CA authority. With Azure IOT Edge I have not yet been able to integrate additional certificates. As a result, the EDGE Agent container cannot establish a connection because it fails behind the firewall due to a certificate error. Without a deep-packet-inspection firewall, however, the tested connections run properly. 
Is there a way to integrate certificates from such proxies into all AZURE IOT EDGE modules automatically, or at least into the EDGE AGENGT container? (e.g. via docker volume mounting or something else )

**Comment by darobs** [comment]
Hello @SergeiIkkert 

We think this is a scenario we wouldlike to support, and we're looking into ways to do that.  I put this issue into our backlog so that it gets triaged.

Thank you.

**Comment by aribeironovaes** [comment]
HI @SergeiIkkert , 

Closing this issue here since it's related to v2, can you please open it here, or at Microsoft User Voice so we can get your request at the proper place? 

Also, According to @darobs  it is in our backlog, so we won't lose it. 

Thanks, 

Angelo Ribeiro.
