### ISSUE TITLE
[V1] Microsoft azure IOT Edge 

### ISSUE THREAD

**Issue by kiran240** [Azure/iot-edge-v1#557]
Hi,
``
I am working on Eclipse IDE for the Microsoft azure Edge IoT with the C based code.But the source code which is in the Azure repository is in dot net and java and c  languages and dependencies and am unable to compile in the Eclipse. 
Can anybody  please suggest how to work on Device level and cloud level by using only C so to integrate with the sensors at edge level and cloud level.
or Is there any IDE to compile the code instead of Eclipse.
My system is of 32bit type
``

Thanks&Regards
Kiran

**Comment by darobs** [comment]
Hello @kiran240 

Are you looking for the V1 or V2 edge?  The V1 core code is in C, but we have bindings in dotnet and Java (and node). You shouldn't need to compile the bindings to get the core functionality. 

The project is set up using CMake files, [this Cmake.org page on CMake and eclipse](https://cmake.org/Wiki/CMake:Eclipse_UNIX_Tutorial) might help, but no one on the Edge team are Eclipse users.  

Does this help get you on the right track?

**Comment by kiran240** [comment]
hello@**darobs**
```
Yes I am looking for the V1 edge which is C only. 
I will try to compile without using the bindings.thanks for your support.
```
Thanks&Regards
Kiran

**Comment by kiran240** [comment]
hello@darobs
We tried to compile with our ubuntu14.04 using c make files.I think it's buildedup correctly
We are trying to make the source code working at edge level.

 I would be pleased if you could give any suggestions how to run on linux ubuntu terminal..

**Comment by darobs** [comment]
Hello @kiran240 

What do you need help with?  I think the only trouble we've had with 14.04 is the default GCC compiler was a bit old and needed to be updated.

**Comment by aribeironovaes** [comment]
Closing to lack of activity. 
Please, do open again if you still have this problem.
