### ISSUE TITLE
[V1] Upgrade request: dotnetcore modules to based on netcore2.0

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge-v1#567]
In the 6 csproj files in `v1/bindings/dotnetcore` and `v1/samples` folders, I edited the `<TargetFramework>` tag and was able to build dotnetcore modules based on 2.0. I also removed both `<RuntimeFrameworkVersion>` and `<PackageTargetFallback>` tags present in csproj files. 

I am _very_ new to dotnet and likes to know if this Is this the correct way to upgrade to netcore2.0? If yes, I will put a pull request. I will test on both Ubuntu 16.04 and macOS 10.12.3.

**Comment by darobs** [comment]
Yes, please do the pull request.

**Comment by damonbarry** [comment]
@kiranpradeep closed the PR, so I'll close this as well.
