### ISSUE TITLE
[V2] System.NullReferenceException at CloudProxy.SetupCallMethodAsync() in edgeHub

### ISSUE THREAD

**Issue by matsujirushi** [Azure/iot-edge-v1#572]
Hello, 

I run [this tutorial](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-stream-analytics), 
I have below error using Ubuntu 16.04 on UP2.

```
2018-04-04 10:20:38.117 +00:00 [WRN] - Error adding subscription $iothub/methods/POST/# for client seeed-iotedge2/tempSensor.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.SetupCallMethodAsync() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 132
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.SessionStatePersistenceProvider.<>c__DisplayClass10_0.<<ProcessSessionSubscriptions>b__0>d.MoveNext() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/SessionStatePersistenceProvider.cs:line 66
Illegal instruction (core dumped)
```

Could you tell me how to get some information from edgeHub?

Thanks.

**Comment by matsujirushi** [comment]
See below:

1. Install Ubuntu 16.04 to UP Squared board
https://downloads.up-community.org/download/up-squared-iot-grove-development-kit-ubuntu-16-04-server-image/

2. Disable IPv6
```
$ sudo vi /etc/sysctl.conf
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
$ sudo sysctl -p
```

3. Upgrade pip
```
$ sudo apt-get update
$ sudo apt-get install python-pip
$ sudo pip install --upgrade pip
```

4. Install Docker
```
$ curl -fsSL get.docker.com -o get-docker.sh
$ sudo sh get-docker.sh
$ sudo usermod -aG docker upsquared
$ exit
```

5. Setup ASA sample.
https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-stream-analytics#create-an-azure-stream-analytics-job

6. Run IoT Edge Runtime
```
$ sudo -H pip install -U azure-iot-edge-runtime-ctl
$ sudo iotedgectl setup --connection-string "..." --auto-cert-gen-force-no-passwords
$ sudo iotedgectl start
```

**Comment by dsajanice** [comment]
This issue has been fixed and will be in the next release. Please monitor https://hub.docker.com/r/microsoft/azureiotedge-hub/tags/ for our next release 1.0.0-preview023. As we understand it, this issue should not block any workflow on IoT Edge. Please let us know if that is not the case.

**Comment by damonbarry** [comment]
Fixed. Closing...
