### ISSUE TITLE
Feature request: POSIX manpage missing for iotedgectl

### ISSUE THREAD

**Issue by polarapfel** [Azure/iot-edge-v1#584]
There is no manpage for iotedgectl.

**Comment by myagley** [comment]
Thank you for reporting this. Manpages are near and dear to our heart. This will be addressed before the GA release. Stay tuned.

**Comment by damonbarry** [comment]
`iotedgectl` has been superseded by `iotedged` for GA. And `iotedged` has a manpage. 🎉 Closing...
