### ISSUE TITLE
iotedgectl has Python dependency version conflicts that cause failures

### ISSUE THREAD

**Issue by hxlnt** [Azure/iot-edge-v1#585]
**Version** IoT Edge v2

**Device** Raspberry Pi Model 2, ARM v7, Raspbian Lite

**What I did** After previously installing `python-pip,` `python2.7-dev,` `libffi-dev,` `libssl-dev,` `docker,` and `setuptools`
```
sudo pip install -U azure-iot-edge-runtime-ctl
sudo iotedgectl setup --connection-string "{my_connection_string}" --nopass
```
**What I expected** Successful azure-iot-edge-runtime-ctl installation and setup command

**What happened**
  - At the end of azure-iot-edge-runtime-ctl installation:
```
pyopenssl 17.5.0 has requirement cryptography>=2.1.4, but you'll have cryptography 1.7.1 which is incompatible.
requests 2.18.4 has requirement idna<2.7,>=2.5, but you'll have idna 2.2 which is incompatible.
Installing collected packages: websocket-client, backports.ssl-match-hostname, urllib3, chardet, certifi, requests, docker-pycreds, pyOpenSSL, docker, azure-iot-edge-runtime-ctl
Successfully installed azure-iot-edge-runtime-ctl-1.0.0rc22 backports.ssl-match-hostname-3.5.0.1 certifi-2018.4.16 chardet-3.0.4 docker-3.0.0 docker-pycreds-0.2.3 pyOpenSSL-17.5.0 requests-2.18.4 urllib3-1.22 websocket-client-0.47.0
```
  - Upon running iotedgectl setup:
```
Traceback (most recent call last):
  File "/usr/local/bin/iotedgectl", line 11, in <module>
    sys.exit(coremain())
  File "/usr/local/lib/python2.7/dist-packages/edgectl/__init__.py", line 23, in coremain
    version = pkg_resources.require(PACKAGE_NAME)[0].version
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 1.7.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('cryptography>=2.1.4'), set(['pyOpenSSL']))
-bash: --nopass: command not found
```

**Workaround** Uninstall and reinstall idna and pyopenssl.
```
sudo pip uninstall idna pyopenssl -y
sudo pip install idna pyopenssl
```
After executing the commands above, iotedgectl setup works fine.

**Comment by matsujirushi** [comment]
Can you try this setup guide?
http://matsujirushi.hatenablog.jp/entry/2018/04/15/214721

**Comment by polarapfel** [comment]
I ran into the same issue.

The cryptography Python dependency on Debian's Python 2.7 can be resolved fairly easy.

First, make sure you have everything available on your Pi to build what you need:

`sudo apt-get install build-essential libssl-dev libffi-dev python-dev`

Then, you instruct pip to install the cryptography library from sources. It will pull whatever the latest stable version is (you can also use pip's version pinning if you like):

`sudo pip install cryptography --no-binary cryptography`

This will not install the default 1.7.1 but at the time I wrote this it should be 2.2.2.

--

The greater root problem to this particular dependency issue tied to the mess that Python's package management across two largely incompatible Python versions is (Python 2 versus Python 3).

With the current state of the Python ecosystem and the fact that all major stable branches of Linux distributions still default to Python 2.7, I would have hoped for the following from IoT Edge:

- Provide a requirements file for pip with pinned versions of dependencies for both Python 2.7 and Python 3.6.x. that have been tested against both
- Or provide installation bundles that have been tested using pip wheel, for both Python 2.7 and Python 3.6.x.

**Comment by hxlnt** [comment]
Yes, I think all three of us essentially have posted different workarounds to accomplish the same end goal and have all gotten `edgeiotctl` running on the RPi. That's the good news! :)

My hope is--to @polarapfel's point--that the `iotedgectl` tool could resolve these version issues out of the box so that there's less friction for new users. Thanks!

**Comment by hxlnt** [comment]
Additionally, this same issue occurs on an x86 Linux machine running Ubuntu 16.04 and Python 2.7. Same workaround works.

**Comment by aribeironovaes** [comment]
HI @hxlnt , 

Closing this issue. After GA iotedgectl has been deprecated for production (We have iotedge security daemon now). 

Also, if you see any issue on v2, can you please open on the v2 github? 

Thanks a lot for using azure iot edge, 

Angelo Ribeiro.
