### ISSUE TITLE
IoT Edge (preview) device details blade in the Azure Portal is down (EdgeDeviceBlade MICROSOFT_AZURE_IOTHUB)

### ISSUE THREAD

**Issue by mschulz531** [Azure/iot-edge-v1#588]
IoT Edge (preview) device details blade in the Azure Portal is down...when I click on a device in the list of IoT Edge devices, a new blade opens up that shows "EdgeDeviceBlade MICROSOFT_AZURE_IOTHUB" and a cloud with a raindrop.  
I am unable to manage a device...unable to push an updated container, etc.
Anyone else seeing this?
It happens on multiple IoT Hubs

**Comment by varunpuranik** [comment]
It might have been a transient thing - it seems to be working fine for me now. Can you please clear your cache and try again?

**Comment by HenrikBach1** [comment]
Hi,

I also had the above described problem yesterday, and for a moment ago. 

Clearing my browsing cache did the job. Now, it works as expected.

/Henrik

**Comment by termocontrole** [comment]
Hi,

Same problem here.

I cleaned the browser cache and everything is working perfectly

**Comment by mschulz531** [comment]
Confirmed - same action worked for me: clear browser cache, close and reopen browser; Device Details blade then opened normally.
Is is possible to show a more helpful message in the blade that would help us to know this is a browser cache issue?  Showing a cloud with a raindrop does communicate that an error occurred, but doesn't provide any advice about how to resolve the problem.

**Comment by myagley** [comment]
Closing as this is no longer an issue in the portal.
