### ISSUE TITLE
[V2] Get Host IP Address in Modules

### ISSUE THREAD

**Issue by danigian** [Azure/iot-edge-v1#616]
- **V2** 

- **OS version and architecture used:** Ubuntu / ARM64

- **Version used:** V2 - 1.0.0-preview022 -->

- **V2 Docker version and container type** 18.05.0-ce with linux containers

# Description of the issue:
In order to enable containers to host communication we should have the possibility to retrieve the host IP address in the Edge Modules. At the moment this is not feasible in an easy way (the easiest should be mounting a text file from the host filesystem)​

**Comment by mrohera** [comment]
This seems like a reasonable request. Would hostname work for you instead? If you really need IP, can you please state why? It would be good to understand the reasons.

**Comment by mrohera** [comment]
We will add this request to our task list.

**Comment by danigian** [comment]
@mrohera hostname would be perfect too

**Comment by mrohera** [comment]
We have implemented the hostname piece for modules and will be released with our June release. The way to query this within an Edge module would be via env variable IOTEDGE_GATEWAYHOSTNAME. This hostname would be data that would be configured by the deployer of the Edge runtime.

If the hostname (or for that matter any configuration) were to be ever modified, the entire deployment would be recreated. This way modules will always be in sync with what is explicitly configured.

**Comment by myagley** [comment]
Hello, this has now been released as part of the GA of IoT Edge. There are some changes required to the installation that are required to migrate from the Public Preview. You can learn more here: https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux
