### ISSUE TITLE
Host restart - messaging failure

### ISSUE THREAD

**Issue by davebanthorpe** [Azure/iot-edge-v1#619]
OK so yesterday I deployed a couple of modules to a new edge device. Everything was working fine throughout the day. After rebooting the host this morning I no longer see any messages flowing to/from the hub. The downstream module (connecting to the sensors) is reporting sampled data OK but no data is routing via the hub.

I have left it for a couple of hours and if I look at the hub logs I recently saw this entry:

```
2018-06-06 09:52:23.705 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint dev/pifunc/input1
2018-06-06 09:52:23.769 +00:00 [INF] - Cleaned up 541 messages from queue for endpoint dev/pifunc/input1 and 0 messages from message store.
2018-06-06 09:52:53.772 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint dev/modbus/input1
2018-06-06 09:52:53.773 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint dev/modbus/input1 and 0 messages from message store.
2018-06-06 09:53:23.776 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
2018-06-06 09:53:23.831 +00:00 [INF] - Cleaned up 559 messages from queue for endpoint iothub and 541 messages from message store.
```

To me this implies that that hub has stalled as it has failed to route messages from the modbus (downstream) module to my function module as well as routing messages to the upstream iothub.

Stopping the edgeHub module, removing it from docker and then letting Azure automatically redeploy it does not rectify the issue. The ONLY resolution is to stop and delete both edgeHub and edgeAgent and re-run "iotedgectl setup"

Any idea what has caused this and how to rectify?

**Comment by varunpuranik** [comment]
Thanks for reporting this issue. We have some fixes in our upcoming release that should fix these issues. You should be able to get that in the coming few weeks (I don't have an exact date yet). 

If you can provide us with the details of your topology (the modules that were deployed and the routes that were set up), I can make sure the scenario works with the latest bits.

**Comment by davebanthorpe** [comment]
Sure - modules are:

microsoft/azureiotedge-modbus-tcp:1.0-preview
and my own C# module (called pifunc) hosted out of my own repository. 

My module looks at the data reported from modbus and if temperature within a certain range sends a message back to modbus module to set a flag in the modbus registers.

routing is:

```
{
  "routes": {
    "modbusToFunction": "FROM /messages/modules/modbus/outputs/modbusOutput INTO BrokeredEndpoint(\"/modules/pifunc/inputs/input1\")",
    "modbusToCloud": "FROM /messages/modules/modbus/outputs/modbusOutput INTO $upstream",
    "functionToModbus": "FROM /messages/modules/pifunc/outputs/* INTO BrokeredEndpoint(\"/modules/modbus/inputs/input1\")"
  }
}
```

**Comment by varunpuranik** [comment]
Cool, thanks.

**Comment by damonbarry** [comment]
Should be fixed with GA release. Please try again and reopen if you see this on the latest bits. Thanks!

**Comment by ddobric** [comment]
Today, I noticed the same issue.
Have iotedge gateway running for days. After restart, messages are no more routed to one module.

> 2018-09-03 20:22:33.313 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint ai-01-amd64/XYMODULE/input1
> 2018-09-03 20:22:33.986 +00:00 [INF] - Cleaned up 568 messages from queue for endpoint dev-41-amd64/XYMODULE/input1 and 568 messages from message store.
> 2018-09-03 20:23:03.985 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
> 2018-09-03 20:23:03.985 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint iothub and 0 messages from message store.

There is no any error or warning in any of logs. Have another module, which performs well and routes messages to XYMODULE/input1. Unfortunately, messages never arrives in XYMODULE. 

Using Agent and Hub v1.0 on Windows10/Linux containers.
