### ISSUE TITLE
GetModulesOnDeviceAsync and SELECT * from devices.modules Returns Ghosted Modules

### ISSUE THREAD

**Issue by jason-e-gross** [Azure/iot-edge-v1#624]
- **OS version and architecture used:** <VERSION> ALL

- **Version used:** <VERSION> Latest (1.16.x-preview-004)

# Description of the issue:
When Using `registryManager.GetModulesOnDeviceAsync` or `.CreateQuery("("SELECT * FROM devices.modules WHERE deviceId='XXXX'")`;

They return modules that are no longer on the device.    If we add a module, use it for a bit, then remove it (through the Azure Portal) -- the module twin that was removed is still returned with this - even weeks and months later.

The module isn't listed in the $edgeAgent's modules section of reported/desired properties.  The module isn't listed in the IOT Edge section for the device in Azure Portal.  The module isn't physically on the device's docker container or images - but yet these commands bring its module twin back in the query.    For all intents and purposes - this module is no longer part of our system or function - but still comes back in this query, making the queries useless to us -- we can't programmatically iterate through modules on a device and depend on this information.   

 Imagine deleting a row in a database table, but always getting that row back every time we query the table.   That's what this is.

Why would I want to see a module that I added two months ago, removed 1.5 months ago - show up in a query to get me the modules for a device?   Of what use is this?     
Imagine deleting a row in a database table, but always getting that row back every time we query the table.   That's what this is.     Why would Microsoft be hanging on and reporting this information, when it's of no use to us.

**Comment by jason-e-gross** [comment]
The modules were only added and removed through the Azure Iot Hub Portal set modules process.   It's code in other places (using registry Manager in a web api to get a list of modules on a device) that is revealing the ghosted modules and their twins.

It seems counter intuitive that we add and remove modules via the portal, but also have to remove them via code to make them REALLY gone.   That's a hard disconnect between the two, especially when the ghosted modules twin looks normal and gives no sign that it's not active.

________________________________

**Comment by varunpuranik** [comment]
The idea is that all operations done within the SetModules process affect the "deployment", and not the actual identities. So removing a module there, simply removes it from the deployment.
But in any case, thanks for the feedback, we will look at making it clearer and more intuitive.

**Comment by varunpuranik** [comment]
I will close this issue. If you run into any other issues, feel free to open another one.
