### ISSUE TITLE
DeviceClient/ModuleClient .OpenAsync Timeouts or Delays with .NET Core 2.1

### ISSUE THREAD

**Issue by jason-e-gross** [Azure/iot-edge-v1#625]
- **OS, version, SKU and CPU architecture used:** Windows 10 64 bit, Linux Ubuntu 16.04 (the delay appears in both).
- **Application's .NET Target Framework :** netcoreapp21
- **Device:** AMD64 machines

## Description of the issue:
When updating the IOT Edge project to use .NET Core 2.1, it introduces delays and timeouts in devices or modules at .OpenAsyc.         About 30% timeouts to crashing (which edgeAgent restarts the module) to 70% delays of over 20-30 seconds or more.

## Code sample exhibiting the issue:
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0" />

It shows in either:
~~~~
<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.17.0-preview-007" />
~~~~
or 
~~~~
<PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.6.0-preview-001" />
~~~~

If we downgrade back to .NET Core App 2.0, the timeout/delay goes away, and .OpenAsync is as quick as you would expect it to be.      It exhibits itself in three modules we tried updating - which range from nothing more special than the FilterModule example to one that uses Kestrel/SignalR (port 8012).  

Updating to the 1.17.0-preview-007 has made it *less* likely to timeout and crash the module, but it still takes over 20 seconds.   An example of a timeout is below (4 mins passed before it crashed).   Includes a .ContinueWith to capture the stack trace.

~~~~
06/15/2018 14:02:22 | INIT: Opening ModuleClient
06/15/2018 14:06:23 | INIT: ModuleClient Initialized, CW: {"Id":1,"Exception":{"ClassName":"System.AggregateException","Message":"One or more errors occurred.","Data":null,"InnerException":{"ClassName":"System.TimeoutException","Message":"Operation timeout expired.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233083,"Source":"Microsoft.Azure.Devices.Client","WatsonBuckets":null},"HelpURL":null,"StackTraceString":null,"RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233088,"Source":null,"WatsonBuckets":null,"InnerExceptions":[{"ClassName":"System.TimeoutException","Message":"Operation timeout expired.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233083,"Source":"Microsoft.Azure.Devices.Client","WatsonBuckets":null}]},"Status":7,"IsCanceled":false,"IsCompleted":true,"IsCompletedSuccessfully":false,"CreationOptions":0,"AsyncState":null,"IsFaulted":true}
06/15/2018 14:06:23 | INIT: DeviceClient StateChange Handler Enabled
~~~~

**Startup.cs**
~~~~
        public void ConfigureServices(IServiceCollection services)  {
            services.AddMvc();
            services.AddCors();
            services.AddSignalR();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env) {
            if (env.IsDevelopment())    app.UseDeveloperExceptionPage();

            app.UseFileServer();
            app.UseStaticFiles(
                new StaticFileOptions    {
                    FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "resources")),    //physical
                    RequestPath = "/resources"                                                                              //pseudo
                }
            );
            app.UseCookiePolicy();
            app.UseCors(builder =>
                builder
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowAnyOrigin()
            );
            app.UseSignalR(routes => {routes.MapHub<UserInterfaceHub>("/uihub");});
            app.UseMvc();
        }
~~~~
**relevant Program.cs**
~~~~
            moduleClient = ModuleClient.CreateFromConnectionString(connectionString, settings);
			await moduleClient.OpenAsync().ContinueWith(_result =>
                Console.WriteLine($"{DateTime.Now.ToString()} | INIT: ModuleClient Initialized, CW: {JsonConvert.SerializeObject(_result)}")
             );
            moduleClient.SetConnectionStatusChangesHandler(onConnectionChange);
~~~~

Dump of console.log (showing 30 second delay -- with .NET Core 2.0, it's instant):
~~~~
06/20/2018 11:52:42 | INIT: Opening ModuleClient
06/20/2018 11:53:10 | INIT: ModuleClient Initialized, CW: {"Id":1,"Exception":null,"Status":5,"IsCanceled":false,"IsCompleted":true,"IsCompletedSuccessfully":true,"CreationOptions":0,"AsyncState":null,"IsFaulted":false}
~~~~

**Comment by damonbarry** [comment]
What happens if you use the stable release of ModuleClient (`1.17.0`) rather than the preview release?

**Comment by jason-e-gross** [comment]
Same issue.

It exhibits itself in Linux or Windows, and if you use core 2.1 with GA and iotedgectl.  It shows in. Net core 2.o with GA.

It goes away (down to 5 to 10 sec times) if flipping to AMQP.   It seems to be related to MQTT.

________________________________

**Comment by damonbarry** [comment]
Interesting...not seeing this in my development (.NET Core 2.1 on Windows, Ubuntu 16.04/18.04, Raspbian Stretch Lite).

Are you only seeing this for devices or modules connecting to Edge Hub? Or do you also see it when a device or module client connects directly to IoT Hub?

Do you have a self-contained minimal repro of this?

**Comment by damonbarry** [comment]
It would be great to have the links to other reports of this same issue.

BTW, besides upgrading your modules to .NET Core 2.1, did you also upgrade them to IoT Edge GA? Specifically, I mean upgrading the modules to work with iotedged (our new security daemon for GA) instead of iotedgectl (which is preview-only) by using `ModuleClient.CreateFromEnvironmentAsync` instead of `CreateFromConnectionString`? You can look [here](https://github.com/Azure/iotedge/tree/master/edge-modules) to see the updates we made to `SimulatedTemperatureSensor` and `TemperatureFilter`.

**Comment by damonbarry** [comment]
@jason-e-gross Talking to some other people on my team, it sounds like this is a known issue, as you pointed out, in the module client's MQTT codepath, and possibly .NET Core 2.1. The module client repo is this best place to track this, and since you already created Azure/azure-iot-sdk-csharp#521 for this purpose, I'll close this issue in favor of that one.

FYI @CIPop @varunpuranik

**Comment by jason-e-gross** [comment]
That's what I was going to link, thanks Damon.  Appreciate it.

________________________________

**Comment by jason-e-gross** [comment]
Yes and yes.  We've been on GA and FromEnvironment twenty minutes after it hit GA.  We were module Client before GA hit, then switched to FromEnvironment off connectionstring the moment it landed.

When we switched to GA, we also kicked everyone to core 2.1, and then saw the timeouts across the board (iotedgectl saw it only with 2.1).  It was only when we flipped off mqtt for both (ga and iotedgectl) that we saw the timeouts stop happening.

AMQP still takes around 10 seconds, and it does seem like if I rebuild the device from scratch it is quicker and slowly degrades over time, meaning the more I restart the service, the longer it gets. (stopping and restarting maybe 30 to 40 times daily) but that last bit could just be a placebo observation.

________________________________

**Comment by CIPop** [comment]
Thanks @damonbarry : we've upgraded all our DeviceClient SDK testing to go against 2.1 yesterday and we saw no timing issues in our CI system.
I'm now focusing on trying to understand what is the particular configuration in iotedge causing the issue.

For everybody that hits the issue, please continue the discussion at https://github.com/Azure/azure-iot-sdk-csharp/issues/521
