### ISSUE TITLE
How does one instantiate a deviceclient in the device app using environment variables?

### ISSUE THREAD

**Issue by vbadri** [Azure/iot-edge-v1#646]
Hello,
Module clients can be instantiated by using..

ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);

However, there is no mechanism to instantiate a DeviceClient using environment variables. The only method that seems to work is..

ioTHubDeviceClient = DeviceClient.CreateFromConnectionString(DeviceConnectionString, TransportType.Mqtt);
            
However, this involves loading a DeviceConnectionString on each device which is obviously not scalable. Is there an accepted solution for this? 

- **V1 or V2 issue** 

- **OS version and architecture used:** <VERSION> 
<Architecture> 

- **Version used:** <VERSION> 

- **V2 Docker version and container type** <VERSION> <TYPE> 

# Description of the issue:

# Console log of the issue:

**Comment by darobs** [comment]
Hello @vbadri  

Thank you for the suggestion. This has been discussed in our team, but it was not prioritized for GA.

The best place for this suggestion would be on [User Voice](https://feedback.azure.com/forums/321918-azure-iot) so we can prioritize these requests.  

I'm going to close this, as this would be an enhancement on the [Azure IoT C# SDK](https://github.com/Azure/azure-iot-sdk-csharp).

**Comment by vbadri** [comment]
Thanks, David. Will post it here, but I'm confused about one thing.  What is the recommended way to solve the problem now?  Seems like a fairly basic thing to instantiate a device client at each device. How do you guys distribute the identity to each device?

**Comment by darobs** [comment]
In general, I would say that safely assigning identity is something we would recommend using the [Azure IoT DPS service](https://docs.microsoft.com/en-us/azure/iot-dps/).  This feature allows assignment of unique identities to devices at scale.  

In specific, for leaf devices on IoT Edge? We would expect leaf devices to be running in processes outside of containers, so the edgeAgent would **not** be creating the process and it would **not* provide information for obtaining the device identity through environment variables.  We do not have a best practice defined for leaf devices, but DPS on leaf devices is a feature on our backlog.

**Comment by vbadri** [comment]
Got it. I was asking about leaf devices. Tahnks.  Will add the feature request to user voice.

**Comment by vbadri** [comment]
FWITW, here's one way to get around the problem. 

In the docker deployment file, change the createOptions field for your module to mount the config file from the host. Note that source file is config1.yaml which is the same thing as config.yaml but with read permissions for all users (you can also change the read permissions of config.yaml, but I didn't want to do it). The copiedConfig.yaml file can now be used to derive teh connection string. 

 "createOptions": "{\"HostConfig\":{\"Binds\":[\"/etc/iotedge/config1.yaml:/app/copiedConfig.yaml\"]}}"
