### ISSUE TITLE
Tutorial required to create our own simulated sensor

### ISSUE THREAD

**Issue by NayangiriGoswamiGit** [Azure/iot-edge-v1#649]
The temperature sensor image is there but as docker container having dll files.
Now if I want to publish weather info instead of temperature and pressure, there is no proper guide to create such sample.

**Comment by aribeironovaes** [comment]
Hi @NayangiriGoswamiGit , 

First, If you feel that this doesn't answer your question, can you please open an issue on v2 version of github: https://github.com/Azure/iotedge/issues

So, The temperature sensor is open source here, https://github.com/Azure/iotedge/tree/master/edge-modules/SimulatedTemperatureSensor. So, in case you want to build your own custom Temperature Sensor you can just change this and publish your own module. 

To do that you can follow what is described on custom module documentation: 
https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module

Let me know if you need any more specific help. I will close this issue so you can open one on v2 github if you feel it's needed. 

Thanks! 

Angelo Ribeiro.
