### ISSUE TITLE
Cannot Send or receive messages after deploying IoT Edge

### ISSUE THREAD

**Issue by samisarfraz** [Azure/iot-edge-v1#652]
I have couple of questions:

1.	I have successfully configured IoT Edge on raspberry Pi 3; Linux os and able to connect leaf device with IoT edge (I can see my device connected on Azure IoT Portal but I cannot receive or send command using direct method from device explorer (IoT Hub).

If I take out IoT edge then I can receive message and send commands using device explorer (IoT hub).

2.	I would like to know that if I create an android app to control & monitor my devices (send command using direct method and receive messages from devices). Communication flow will be android app ---> IoT Hub ---> IoT Edge ---> Leaf Device (bi-directional communication) and if internet link is down but android user, IoT edge and Leaf Devices are all connected to same AP (network) then I will be able to send commands and receive message from device? Communication flow will be android app ---> IoT Edge ---> Leaf Device (bi-directional communication). MQTT

**Comment by aribeironovaes** [comment]
HI @samisarfraz , 

First, can you update your bits with the latest release? We just released a bunch of fixes that may address your issue. 
Second, if you still see an issue, can you please check if there is an issue opened on: https://github.com/Azure/iotedge/ ? This is the v2 github, so we are trying to get the issues on v2 addressed to that github. 

I'm closing this one so you can reply to existing issue there or creating a new one. 

Thanks a lot! 

Angelo Ribeiro.
