### ISSUE TITLE
IOT-Edge Hub back-off state

### ISSUE THREAD

**Issue by BilalAkmal47** [Azure/iot-edge-v1#654]
i am trying to deploy a module into iot-edge device, for that i am following these [Official Documentation](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart). 
- Have an IoTHub subscription
- Created Edge Device in it
- Installed IoTEdge Runtime on my local machine (to act it like as a simulated device)
- Docker for windows is installed, up and running
(Everything works well till here, as i checked the status of `Get-Service iotedge` command)
- Set up the Device module and used this `mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0` as an image

after setting up the module on Microsoft Azure portal, edgeHub Module goes into back-off state. i have seen this issue [IOT-Edge Hub back-off state](https://github.com/Azure/iot-edge-v1/issues/531) and tried to restart docker as some of the comments suggested, but all in vain. 
i have also run the `docker logs edgeAgent` command to show you some logs, which are attached with this post.
[logs.txt](https://github.com/Azure/iot-edge-v1/files/2339847/logs.txt)

Azure portal Status  
![2](https://user-images.githubusercontent.com/6631670/44910133-7d337480-ad3b-11e8-89b0-de072483f387.png)

![1](https://user-images.githubusercontent.com/6631670/44910142-8ae8fa00-ad3b-11e8-85b2-6f1882bbc1ed.PNG)

iotedgeruntime status

![3](https://user-images.githubusercontent.com/6631670/44910147-93d9cb80-ad3b-11e8-896e-3af926b69599.PNG)

**Comment by aribeironovaes** [comment]
Thanks for the report @BilalAkmal47 , 

Can you please open an issue here: https://github.com/Azure/iotedge ? 

We are trying to move all our issues related to v2 from this page to the proper github, so it's easier to manage issues. 

I'm going ahead and closing this here, so we can follow up there. 

I will take a look into your logs there.

**Comment by BilalAkmal47** [comment]
Thanks. I have opened this issue at: [https://github.com/Azure/iotedge/issues/240](https://github.com/Azure/iotedge/issues/240)
