### ISSUE TITLE
IoT Edge docker failure on Windows IoT Core Build Version- 10.0.17763.17 

### ISSUE THREAD

**Issue by pratson20** [Azure/iot-edge-v1#659]
Hi,

I am facing issue on docker issue on IoT Core. Installation of docker and edge was completed successfully. Followed below link to install docker and Edge runtime-
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-core

Failure Log on running below Command-
Invoke-WebRequest https://master.dockerproject.org/windows/x86_64/docker-0.0.0-dev.zip -o temp.zip
Expand-Archive .\temp.zip $env:ProgramFiles -f
Remove-Item .\temp.zip
$env:Path += ";$env:programfiles\docker"
SETX /M PATH "$env:Path"
dockerd --register-service
start-service docker

I am using Aaeon gateway

Kindly help me to resolve this issue

Attaching detailed log

`
[Edge_Installation_Log (1).txt](https://github.com/Azure/iot-edge-v1/files/2539824/Edge_Installation_Log.1.txt)

[Edge_Installation_Log.txt](https://github.com/Azure/iot-edge-v1/files/2539823/Edge_Installation_Log.txt)
`

**Comment by damonbarry** [comment]
Hi @pratson20. We're not actively monitoring for IoT Edge **v2** issues in this repo. Given that you were following a tutorial on docs.microsoft.com, the best way to get help is to:
- go to the "Feedback" section at the bottom of the tutorial page
- click the dropdown button and select "leave feedback directly on GitHub".
This will allow you to file a GitHub issue against the docs.
