### ISSUE TITLE
It seems that Desired Properties doesn't work

### ISSUE THREAD

**Issue by Warlib1975** [Azure/iot-edge-v1#660]
Hello, 

when I updated properties (https://github.com/Azure/iot-edge-v1/tree/master/v2/samples/azureiotedge-simulated-temperature-sensor#desired-properties-support-new) in Module Identity Twin at the Azure Portal nothing happened for tempSensor. 

I even did iotedge restart tempSensor - nothing happened. At the example I had changed in Module Identity Twin JSON properties -> desired: SendInterval from 5 to 7:

 "properties": {
    "desired": {
      "SendData": true,
      "SendInterval": 7,
…
Nothing changes in interval. 

PS C:\WINDOWS\system32> docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Image}}"
CONTAINER ID        NAMES               IMAGE
7ef16ac14a76        edgeHub             mcr.microsoft.com/azureiotedge-hub:1.0
63425d12572d        tempSensor          mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
838cd1e532a4        edgeAgent           mcr.microsoft.com/azureiotedge-agent:1.0

PS C:\WINDOWS\system32> docker --version
Docker version 18.06.1-ce, build e68fc7a

PS C:\WINDOWS\system32> iotedge --version
iotedge 1.0.4 (2835ac47fbb944ba628a5cfe812ff394768842e0)

Thank you.

**Comment by damonbarry** [comment]
Hi @Warlib1975. All IoT Edge v2 work is now happening over at https://github.com/Azure/iotedge; this v2 sample in the v1 repo isn't actively maintained. I'll work on getting it removed to avoid confusion.

To confirm that a custom module can receive desired property updates, please follow the tutorial [here](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module). If that doesn't work as expected, you can file issues directly on that tutorial page.

Thanks!

**Comment by damonbarry** [comment]
2f97092 Removed v2 samples folder

**Comment by Warlib1975** [comment]
Thank you. V2 is work perfect.
