### ISSUE TITLE
Feather m0 mqtt_client timed out waiting for CONNACK

### ISSUE THREAD

**Issue by idanlahat1** [Azure/iot-edge-v1#664]
Hey!

I have two Feather m0 boards. One is working with no issues, I am able to sen, receive and invoke methods from the cloud.
On the other board, with the same firmware, I have an odd issue.
Th board will connect to the cloud, I can see it in the device explorer as connected and also in the portal.
When I send a message to the device after a few seconds the device throws a "mqtt_client timed out waiting for CONNACK". The error only comes up when I send a message, I can run the devise for hours and it wont throw the error until a message is sent to it.
Messages from the device do no make it to the cloud, and when a method is invoked I get an error that the method is not registered. 
The even weirder thing is that every now and them a massage to the device does actually get received.  
I feel like it might be the device, but nothing seems wrong with the board.

I am running the latest sdk for arduino.

Attached the errors. 
![2019-03-03 11_46_05-firmware](https://user-images.githubusercontent.com/44729603/53698498-8ca77f00-3dab-11e9-9d69-3441172615bc.png)
![2019-03-03 11_49_26-firmware](https://user-images.githubusercontent.com/44729603/53698499-8ca77f00-3dab-11e9-965e-5555308e53db.png)

**Comment by damonbarry** [comment]
@idanlahat1 This report seems to be related to the C SDK, not IoT Edge v1. Please file this issue at https://github.com/Azure/azure-iot-sdk-c. Thanks!
